CREATE TABLE IF NOT EXISTS sessions (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    sessionToken TEXT UNIQUE NOT NULL,
    userID INTEGER UNIQUE NOT NULL,
    expiresAt TIMESTAMP,
    FOREIGN KEY(userID) REFERENCES users(id) ON DELETE CASCADE
);